[[redirects]]
  from = "/nl/*"
  to = "/underconstruction.html"
  status = 302

[[redirects]]
  from = "/en/*"
  to = "/underconstruction.html"
  status = 302

[[redirects]]
  from = "/*"
  to = "/underconstruction.html"
  status = 302
